name: Deploy to Firebase Hosting LIVE channel
on:
  push:
    branches:
      - deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout repo
      - uses: actions/checkout@v2

      # build
      - run: npm ci && npm run build

      # deploy preview channel
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KINAMO_3EC0E }}'
          projectId: kinamo-3ec0e
          channelId: live