# Upload sample data
# This workflow can be added to any repo that contains the finished
# data. Idea is that the backend calculates results and pushs to repo.
# this CI will upload

name: upload sample data

on:
  # Remove the upload-script branch once it works
  push:
    branches: [ main, upload-script ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  upload:
    # should be fine
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x
      
      - name: Install
        run: npm i
      
      - name: Run upload.js
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: | 
          cd ./backend
          node upload.js sample_data.json
